// Generated by build-app.js. Keeps the app working offline.
const CACHE='ppl-8711599f15';
const SHELL=['./','index.html','manifest.webmanifest','icon-180.png','icon-192.png','icon-512.png'];
const FONT_CSS="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=Barlow:wght@400;500;600&display=swap";
async function cacheFonts(c){ // best effort: the app still works offline without them, in system fonts
  try{const res=await fetch(FONT_CSS,{mode:'cors'});if(!res.ok)return;await c.put(FONT_CSS,res.clone());
    const urls=[...(await res.text()).matchAll(/url\((https:[^)]+)\)/g)].map(m=>m[1]);
    await Promise.all(urls.map(u=>fetch(u,{mode:'cors'}).then(r=>r.ok&&c.put(u,r)).catch(()=>{})));
  }catch(e){}
}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(async c=>{await c.addAll(SHELL);await cacheFonts(c)}).then(()=>self.skipWaiting()))});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',e=>{
  const r=e.request;if(r.method!=='GET')return;
  const url=new URL(r.url);
  if(url.origin===location.origin){e.respondWith(caches.match(r,{ignoreSearch:true}).then(m=>m||fetch(r)));return} // app files: from the phone first
  if(/^fonts\.(googleapis|gstatic)\.com$/.test(url.hostname)) // fonts: cached copy, refreshed when online
    e.respondWith(caches.open(CACHE).then(async c=>{const m=await c.match(r);const net=fetch(r).then(res=>{c.put(r,res.clone());return res}).catch(()=>m);return m||net}));
});
